# -*- coding: utf-8 -*-
"""Color a escala de grises

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjkRdDRf9UPCJgysF8j8bJxWSBsxrckE
"""

import cv2
# Load the image
image2 = cv2.imread("/content/drive/MyDrive/Proyecto IA/Test 2.jpg")
image3 = cv2.imread("/content/drive/MyDrive/Proyecto IA/Test 3.jpg")

# Convert the image to grayscale
grayscale_image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
grayscale_image3 = cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)

# Save the grayscale image
cv2.imwrite("/content/drive/MyDrive/Proyecto IA/Test 2_ gris.jpg", grayscale_image2)
cv2.imwrite("/content/drive/MyDrive/Proyecto IA/Test 3_ gris.jpg", grayscale_image3)